name: Deploy Frontend to Azure App Service (Code)

on:
  workflow_dispatch: # Cho phép bấm nút chạy thủ công trên GitHub
  push:
    branches:
      - main
      - develop
    paths:
      - 'SEP490_WEBAPP-main/frontend/**'
      - 'SEP490_WEBAPP-main/frontend_v2/**'


env:
  AZURE_WEBAPP_NAME: 'front-end' # Thay bằng tên App Service FE của bạn trên Azure
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies & Build
        run: |
          cd SEP490_WEBAPP-main/frontend_v2
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FE }}
          package: './SEP490_WEBAPP-main/frontend_v2/dist' # Thư mục chứa code sau khi build của Vite